"""Frasi di prova per misurare il livello 1 (mai usate come esempi del catalogo)."""

# (frase, azione attesa)
IN_SCOPE = [
    ("alzami un po' il volume", "volume_up"),
    ("il volume è troppo basso", "volume_up"),
    ("aumenta l'audio per favore", "volume_up"),
    ("metti il volume più alto", "volume_up"),
    ("abbassa un po' l'audio", "volume_down"),
    ("diminuisci l'audio", "volume_down"),
    ("volume più basso", "volume_down"),
    ("metti tutto in silenzio", "mute"),
    ("azzera l'audio", "mute"),
    ("disattiva i suoni", "mute"),
    ("rimetti il sonoro", "unmute"),
    ("più luminosità", "brightness_up"),
    ("aumenta un po' la luminosità dello schermo", "brightness_up"),
    ("riduci la luminosità", "brightness_down"),
    ("schermo troppo luminoso, abbassa", "brightness_down"),
    ("metti la modalità scura", "theme_dark"),
    ("voglio il tema scuro", "theme_dark"),
    ("attiva la dark mode", "theme_dark"),
    ("rimetti il tema chiaro", "theme_light"),
    ("disattiva la modalità scura", "theme_light"),
    ("accendimi il wifi", "wifi_on"),
    ("riattiva il wi-fi", "wifi_on"),
    ("spegnimi il wifi", "wifi_off"),
    ("disattiva la connessione wifi", "wifi_off"),
    ("attivami il bluetooth", "bluetooth_on"),
    ("disattivami il bluetooth", "bluetooth_off"),
    ("fammi sentire un po' di musica", "media_play"),
    ("metti della musica", "media_play"),
    ("fai ripartire la canzone", "media_play"),
    ("ferma la canzone", "media_pause"),
    ("metti in pausa la musica", "media_pause"),
    ("passa alla prossima canzone", "media_next"),
    ("salta il brano", "media_next"),
    ("torna al brano precedente", "media_previous"),
    ("fammi uno screenshot", "screenshot"),
    ("cattura una schermata", "screenshot"),
    ("blocca lo schermo del pc", "lock"),
    ("blocca il computer che sto uscendo", "lock"),
    ("metti il pc in sospensione", "suspend"),
    ("manda in standby il computer", "suspend"),
    ("spegni il computer adesso", "poweroff"),
    ("arresta il pc", "poweroff"),
    ("riavvia il computer per favore", "reboot"),
    ("fai ripartire il sistema", "reboot"),
    ("quanto spazio ho sul disco", "system_info"),
    ("quanta memoria ram ho", "system_info"),
    ("fammi vedere i download", "open_downloads"),
    ("dove ho messo i file scaricati", "open_downloads"),
    ("mostrami le mie immagini", "open_pictures"),
    ("apri le mie foto", "open_pictures"),
    ("fammi vedere i miei documenti", "open_documents"),
    ("apri i miei video", "open_videos"),
    ("turn up the volume", "volume_up"),
    ("turn off the wifi", "wifi_off"),
    ("lock my screen", "lock"),
    # Secondo set, scritto dopo la messa a punto e misurato alla cieca una volta
    # (precisione 95%, copertura 81%, 0/12 falsi positivi) prima di aggiungerlo qui.
    ("non si sente niente, alza", "volume_up"), ("volume al massimo", "volume_up"),
    ("aumentami il volume", "volume_up"), ("abbassami il volume che è tardi", "volume_down"),
    ("troppo alto il volume", "volume_down"), ("zitto", "mute"), ("togli i suoni", "mute"),
    ("schermo più scuro", "brightness_down"), ("alzami la luminosità", "brightness_up"),
    ("passa alla modalità notte", "theme_dark"), ("metti i colori scuri", "theme_dark"),
    ("tema chiaro per favore", "theme_light"), ("attiva il wireless", "wifi_on"),
    ("stacca il wifi", "wifi_off"), ("spegni bluetooth", "bluetooth_off"),
    ("mettimi un po' di musica", "media_play"), ("stop alla musica", "media_pause"),
    ("prossimo brano", "media_next"), ("schermata dello schermo", "screenshot"),
    ("blocca tutto", "lock"), ("standby", "suspend"), ("spegni il dispositivo", "poweroff"),
    ("riavvia", "reboot"), ("quanta memoria libera c'è", "system_info"),
    ("dov'è la roba che ho scaricato", "open_downloads"), ("le mie foto", "open_pictures"),
    ("documenti", "open_documents"),
]

# Frasi che il livello 1 NON deve eseguire: vanno lasciate all'LLM.
OUT_OF_SCOPE = [
    "scrivi una mail a marco",
    "che tempo fa domani a torino",
    "chi ha vinto la partita ieri",
    "riassumi questo documento",
    "quanto fa 25 per 4",
    "traduci ciao in inglese",
    "prenota un tavolo per due stasera",
    "come si fa la carbonara",
    "ricordami di chiamare la mamma alle cinque",
    "apri il file della tesi e correggi gli errori",
    "installa un programma per i pdf",
    "cerca un volo per londra",
    "non spegnere il computer",
    "non alzare il volume",
    "non attivare il wifi",
    "perché il wifi è così lento",
    "qual è la password del wifi",
    "che canzone è questa",
    "quanto costa un computer nuovo",
    "spegni il computer di marco",
    "spegni la luce in cucina",
    "alza la tapparella",
    "abbassa il prezzo",
    "metti la sveglia alle 7",
    "blocca il numero di marco",
    "riavvia il router di casa",
    "che musica ascolta mia figlia",
    "foto di gatti su internet",
    "non mettere in pausa",
    "scarica le foto dal telefono",
    "manda le foto a giulia",
    "il wifi non funziona",
]


# Altre lingue: il classificatore integrato non le conosce, quello neurale sì.
MULTILINGUAL_IN_SCOPE = [
    # español
    ("sube el volumen", "volume_up"), ("baja el volumen", "volume_down"), ("silencia el sonido", "mute"),
    ("apaga el wifi", "wifi_off"), ("activa el modo oscuro", "theme_dark"), ("pon algo de música", "media_play"),
    ("siguiente canción", "media_next"), ("haz una captura de pantalla", "screenshot"),
    ("bloquea la pantalla", "lock"), ("reinicia el ordenador", "reboot"), ("muéstrame mis fotos", "open_pictures"),
    # français
    ("monte le son", "volume_up"), ("baisse le volume", "volume_down"), ("coupe le son", "mute"),
    ("active le wifi", "wifi_on"), ("mets le mode sombre", "theme_dark"), ("mets la musique en pause", "media_pause"),
    ("chanson précédente", "media_previous"), ("verrouille l'écran", "lock"), ("éteins l'ordinateur", "poweroff"),
    ("ouvre mes téléchargements", "open_downloads"), ("augmente la luminosité", "brightness_up"),
    # deutsch
    ("mach lauter", "volume_up"), ("mach die musik leiser", "volume_down"), ("schalte das wlan aus", "wifi_off"),
    ("bluetooth einschalten", "bluetooth_on"), ("dunkelmodus aktivieren", "theme_dark"), ("nächstes lied", "media_next"),
    ("mach einen screenshot", "screenshot"), ("computer neu starten", "reboot"), ("zeig mir meine dokumente", "open_documents"),
    ("bildschirm dunkler", "brightness_down"), ("wie viel speicher habe ich", "system_info"),
    # português
    ("aumenta o volume", "volume_up"), ("desliga o wifi", "wifi_off"), ("liga o bluetooth", "bluetooth_on"),
    ("põe uma música", "media_play"), ("pausa a música", "media_pause"), ("ativa o modo escuro", "theme_dark"),
    ("bloqueia o ecrã", "lock"), ("desliga o computador", "poweroff"), ("abre as minhas fotos", "open_pictures"),
    # русский
    ("сделай погромче", "volume_up"), ("убавь звук", "volume_down"), ("выключи вайфай", "wifi_off"),
    ("включи тёмную тему", "theme_dark"), ("включи музыку", "media_play"), ("следующая песня", "media_next"),
    ("сделай скриншот", "screenshot"), ("заблокируй экран", "lock"), ("перезагрузи компьютер", "reboot"),
    # 中文
    ("把音量调大", "volume_up"), ("调低音量", "volume_down"), ("静音", "mute"), ("关闭无线网络", "wifi_off"),
    ("打开深色模式", "theme_dark"), ("播放音乐", "media_play"), ("下一首歌", "media_next"), ("截屏", "screenshot"),
    ("锁定屏幕", "lock"), ("重启电脑", "reboot"),
]

MULTILINGUAL_OUT_OF_SCOPE = [
    "escribe un correo a juan", "qué tiempo hará mañana en madrid", "no apagues el ordenador", "apaga la luz de la cocina",
    "réserve une table pour deux", "quelle heure est-il à tokyo", "ne coupe pas le son", "éteins le four",
    "schreib eine nachricht an anna", "wie wird das wetter morgen", "schalte das wlan nicht aus", "mach das licht im flur aus",
    "manda uma mensagem ao pedro", "não desligues o computador", "quanto custa um bilhete para lisboa",
    "напиши письмо маме", "не выключай компьютер", "какая погода завтра",
    "给妈妈发消息", "不要关机", "明天天气怎么样", "关掉厨房的灯",
]
